name: Deploy Middleman site to GitHub Pages

on:
  push:
    branches: [main]  # or "master" if you use that

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # or your preferred version

      - name: Install dependencies
        run: bundle install

      - name: Build site with Middleman
        run: bundle exec middleman build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
