name: Deploy Tech Docs to GitHub Pages

on:
  push:
    branches: [main]  # Update if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install latest Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Make setup script executable
        run: chmod +x ./create-test-site.sh
      - name: Run setup script
        run: ./create-test-site.sh

      - name: Build Tech Docs site
        run: bundle exec middleman build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
