name: Test

on: [push, pull_request]

jobs:
  test:
    name: Create test site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false  # we'll install it explicitly

      - name: Upgrade RubyGems
        run: gem update --system

      - name: Install latest Bundler
        run: |
          gem uninstall -aIx bundler || true
          gem install bundler
          echo 'export PATH="$(ruby -e '\''puts Gem.bindir'\''):$PATH"' >> $GITHUB_ENV

      - name: Install dependencies
        run: bundle install --path vendor/bundle

      - name: Make script executable
        run: chmod +x ./create-test-site.sh

      - name: Run create-test-site.sh
        run: ./create-test-site.sh
