name: 🚀 Publish

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ministryofjustice/tech-docs-github-pages-publisher@sha256:30d00879b5c82afa5d76264164db46189fa11d4358b37ca35b6a62e341d62bb7 # v5.1.0
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build site
        id: build
        run: |
          /usr/local/bin/package

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact.tar
          retention-days: 1
          overwrite: true

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.configure_pages.outputs.base_url }}
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Configure Pages
        id: configure_pages
        uses: actions/configure-pages@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deploy_pages
        uses: actions/deploy-pages@v4
